package com.kasun.ui;


//import DBConections.DBCon;
import com.kasun.customer.dao.PersionDAO;
import com.kasun.customer.model.Persion;

import java.sql.SQLException;
import java.util.logging.Logger;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

	/**
	 *
	 * @author ptn
	 */
	public class SearchById extends javax.swing.JFrame {

	    /**
		 * 
		 */
		private static final long serialVersionUID = 1L;
		/**
	     * Creates new form SearchByID
	     */
	    public SearchById() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        jLabel1 = new javax.swing.JLabel();
	        TFID = new javax.swing.JTextField();
	        jLabel5 = new javax.swing.JLabel();
	        jLabel4 = new javax.swing.JLabel();
	        jLabel3 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        TFName = new javax.swing.JTextField();
	        bSearch = new javax.swing.JButton();
	        TFTPNumber = new javax.swing.JTextField();
	        TFSex = new javax.swing.JTextField();
	        TFAddress = new javax.swing.JTextField();
	        jButton2 = new javax.swing.JButton();
	        jButton3 = new javax.swing.JButton();
	        jLabel6 = new javax.swing.JLabel();
	        jButton1 = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jLabel1.setText("Name");

	        jLabel5.setText("TO NUm");

	        jLabel4.setText("Address");

	        jLabel3.setText("Sex");

	        jLabel2.setText("ID num");

	        bSearch.setText("Search");
	        bSearch.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                bSearchActionPerformed(evt);
	            }
	        });

	        jButton2.setText("Back");
	        jButton2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton2ActionPerformed(evt);
	            }
	        });

	        jButton3.setText("Home");
	        jButton3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton3ActionPerformed(evt);
	            }
	        });

	        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
	        jLabel6.setText("Person Search by ID");

	        jButton1.setText("Clear");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton1ActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                        .addComponent(jButton1)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(jButton3)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(bSearch))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(layout.createSequentialGroup()
	                                .addGap(62, 62, 62)
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addComponent(jLabel5)
	                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                        .addComponent(jLabel2)
	                                        .addComponent(jLabel1)
	                                        .addComponent(jLabel3)
	                                        .addComponent(jLabel4)))
	                                .addGap(55, 55, 55)
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                                    .addComponent(TFName, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
	                                    .addComponent(TFID)
	                                    .addComponent(TFSex)
	                                    .addComponent(TFAddress)
	                                    .addComponent(TFTPNumber)))
	                            .addGroup(layout.createSequentialGroup()
	                                .addGap(104, 104, 104)
	                                .addComponent(jLabel6)))
	                        .addGap(0, 79, Short.MAX_VALUE)))
	                .addContainerGap())
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jLabel6)
	                .addGap(34, 34, 34)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(TFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabel2))
	                        .addGap(19, 19, 19)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(TFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabel1))
	                        .addGap(41, 41, 41))
	                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                        .addComponent(TFSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addComponent(jLabel3)))
	                .addGap(21, 21, 21)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel4)
	                    .addComponent(TFAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(18, 18, 18)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel5)
	                    .addComponent(TFTPNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(bSearch)
	                    .addComponent(jButton2)
	                    .addComponent(jButton3)
	                    .addComponent(jButton1))
	                .addContainerGap())
	        );

	        pack();
	    }// </editor-fold>//GEN-END:initComponents

	    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
	        
	    	ApplicationContext context = new ClassPathXmlApplicationContext("Spring-Module.xml");
	     	  
	        PersionDAO persionDAO = (PersionDAO) context.getBean("persionDAO");
	    	
	    	Persion persion;
	    	persion = persionDAO.findByPersionId(TFID.getText());
	    	
	    	TFName.setText(persion.getName());
	        TFSex.setText(persion.getSex());
	        TFAddress.setText(persion.getAddress());
	        TFTPNumber.setText(persion.getTpnum());
	    	
	    }//GEN-LAST:event_bSearchActionPerformed

	    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	        // TODO add your handling code here:
	        new SearchById().setVisible(true);
	        this.setVisible(false);
	    }//GEN-LAST:event_jButton2ActionPerformed

	    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	        // TODO add your handling code here:
	        TFID.setText("");
	        TFName.setText("");
	        TFSex.setText("");
	        TFAddress.setText("");
	        TFTPNumber.setText("");
	    }//GEN-LAST:event_jButton1ActionPerformed

	    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
	        // TODO add your handling code here:
	        this.setVisible(false);
	        new Selection().setVisible(true);
	    }//GEN-LAST:event_jButton3ActionPerformed

	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.JTextField TFAddress;
	    private javax.swing.JTextField TFID;
	    private javax.swing.JTextField TFName;
	    private javax.swing.JTextField TFSex;
	    private javax.swing.JTextField TFTPNumber;
	    private javax.swing.JButton bSearch;
	    private javax.swing.JButton jButton1;
	    private javax.swing.JButton jButton2;
	    private javax.swing.JButton jButton3;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel jLabel6;
	    // End of variables declaration//GEN-END:variables
	}